### ISSUE TITLE
Форк

### ISSUE THREAD

**Issue by ange007** [Dimox/jQueryFormStyler#102]
Создал [форк плагина](https://github.com/ange007/JQueryFormStylerModern), с более адекватной для сторонних разработчиков структурой.

### Отличия от репозитория оригинала:

* Разделение на **dev** и **master** ветки
* Разбивка плагина на составные части и сборка при помощи **Gulp**
* Автоматизация сборки через **Travis-CI**
* Внесены мои правки которые не были приняты в оригинальный репозиторий

### Зачем?
Прекрасно понимаю что у автора примерно так-же происходит сборка и т.д. - но вот только на локальной машине. А так-же исходя из обсуждений здесь - у автора особо нет желания разбираться в git и прочим.

Поэтому решил по крайней мере для себя сделать подобный репозиторий в который буду вносить свои правки которые мне покажутся необходимыми *( таких уже есть несколько штук - и имеются планы на будущее )*, попытаюсь настроить автоматизацию, и по возможности буду следить за изменения в основной кодовой базе.

Надеюсь с лицензией там ничего не намудрил, и возможно автору в будущем таки станет интересным - приведение репозитория в порядок.

**Comment by feonit** [comment]
Порог вхождения в проект увеличен.
Появление новых зависимостей для проекта могут негативно сказаться на его поддержке.
Не привычный стиль кода типа:
				if ()
				{
				}

**Comment by ange007** [comment]
1. Увеличен порог вхождения из-за необходимости сборки? Там же в релизах и в gh_pages всегда автоматически компилируется версия.
2. О каких новых зависимостях речь?
3. По коду да, но мне так удобней и легче код просматривать.
