### ISSUE TITLE
Use of innerHTML and friends can cause xss issues with remotely loaded data

### ISSUE THREAD

**Issue by kewisch** [Dimox/jQueryFormStyler#105]
This plugin makes wide use of constructs like `$('<div' + att.id + ' class="jq-checkbox' + att.classes + '"' + att.title + '><div class="jq-checkbox__div"></div></div>');` and similar using `$()`, `.append()` and `.prepend()`.

This can be an issue if developers using this plugin unsuspectingly set remote data which may contain script tags. Please make changes so that values are set using text-safe methods, e.g. `$("<div/>").attr()` or `.text()`, etc.

**Comment by wagnerand** [comment]
Has this been fixed? In which commit?

**Comment by Dimox** [comment]
Fixed in [this](https://github.com/Dimox/jQueryFormStyler/commit/ae264fc7229f0ddc679e4c7a781ef8b2f595c64d) commit.

**Comment by wagnerand** [comment]
Thank you.
