### ISSUE TITLE
Не срабатывает событие onclick

### ISSUE THREAD

**Issue by evil1** [Dimox/jQueryFormStyler#106]
Добрый день!
Не получается поймать событие onClick на чекбоксе. Судя по коду это происходит из-за того, что styler сам обрабатывает onClick и вызывается preventDefault.
Было бы здорово добавить возможность конфигурировать callback функцию для события onClick.

**Comment by pafnuty** [comment]
Сама идея обработки клика по чекбоксу - не совсем правильна, ведь в чекбокс можно попасть и с клавиатуры.
Ловите событие `change`.

**Comment by evil1** [comment]
Да, уже так и сделал!
Спасибо большое!
Отличный плагин!
