### ISSUE TITLE
Сброс формы

### ISSUE THREAD

**Issue by salexseen** [Dimox/jQueryFormStyler#107]
Когда нажимаем на кнопку с типом reset плагин на это никак не реагирует. Форма сбрасывает все значения, но html код плагина не обновляется. Не плохо было бы иметь метод refresh, который бы обновлял весь html код плагина.

Я говорю только про select. Как работает с другими элементами я не проверял.
Вот пример https://jsfiddle.net/salexseen/bf75j84q/2/ если поменять значение в селекте и нажать на кнопку ничего не происходит.

**Comment by Gal0n** [comment]
Такой метод есть, и он даже так и называется. С официального сайта: 

> При динамическом изменении элементов формы необходимо запустить триггер refresh, например:
> 
> $('button').click(function(e) {
>   e.preventDefault();
>   /* делаем чекбокс неактивным */
>   $('input:checkbox').attr('disabled', true)
>     /* обновляем состояние псевдочекбокса */
>     .trigger('refresh');
> });

Ваш код будет выглядеть примерно так:

>  $(function(){
> 	$('.js-select').styler();
>   $("[type='reset']").on("click", function(){
>     event.preventDefault();
>   	$(this).closest('form').get(0).reset();
>     $('.js-select').trigger("refresh");
>   });
> 
> })
