### ISSUE TITLE
При типе number не передается класс

### ISSUE THREAD

**Issue by KiyoshiSaundo** [Dimox/jQueryFormStyler#110]
![screenshot_1](https://cloud.githubusercontent.com/assets/12862713/16298438/0edd8f52-393e-11e6-960f-ac8a333897f6.png)

**Comment by Dimox** [comment]
Какую версию плагина используете? В 1.7.6 передается.

**Comment by KiyoshiSaundo** [comment]
Вы правы, дело в версии. Использовал версию 1.7.4. Обновил до 1.7.6, в ней все работает.
