### ISSUE TITLE
Incorrect opening of select dropdown

### ISSUE THREAD

**Issue by Gal0n** [Dimox/jQueryFormStyler#111]
If "selectSearch : false" (this setting is active by default) , we always have select dropdown opened to Top, because in this code: 

`if (bottomOffset > (minHeight + searchHeight + 20)) {
	dropDown();
	selectbox.removeClass('dropup').addClass('dropdown');
} `  
variable "searchHeight" is "undefined" and this condition never works. If "selectSearch : true" all  works fine. Please, fix this bug.

**Comment by Dimox** [comment]
Не наблюдаю такого бага.

**Comment by Gal0n** [comment]
Проверил на вашем демо - действительно, все работает. Проблема была с моей стороны. Обычно я все используемые на сайте плагины минифицирую и объединяю в один файл. Если ваш плагин в этом файле идет первым, все работает. Если нет, то searchHeight почему-то выдает undefined ( у вас null) и выпадашка всегда наверх открывается.  Какой-то другой плагин видимо влияет. Спасибо за ответ, тему можно закрывать.
