### ISSUE TITLE
Не скроллится select на тач устройствах

### ISSUE THREAD

**Issue by inoyakaigor** [Dimox/jQueryFormStyler#113]
В выпадающем списке не работает скролл: вместо скролла элементов выпадающего списка скроллится вся страница. Пример на http://video.khl.ru/profile (Выбор сезона).

В проекте используется плагин версии 1.5.3.2 (1.7.6 не подходит, потому что ломает селект).

**Comment by Dimox** [comment]
Про старые версии нет смысла писать.

**Comment by inoyakaigor** [comment]
С последней версией всё тоже самое.

**Comment by Dimox** [comment]
У меня прокручивается.
