### ISSUE TITLE
About package on npm

### ISSUE THREAD

**Issue by pvnr0082t** [Dimox/jQueryFormStyler#114]
Hi @Dimox  ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We want to host this library.
I'd like to confirm that if https://www.npmjs.com/package/jquery.formstyler is officially maintained. If not, we will set git auto-update config and auto-updater in cdnjs will update automatically from git repo not NPM.
Thank you.

https://github.com/cdnjs/cdnjs/issues/9300

**Comment by Dimox** [comment]
https://www.npmjs.com/package/jquery.formstyler is not official.

**Comment by pvnr0082t** [comment]
@Dimox Thank you. :+1:
