### ISSUE TITLE
 if (iOS) return is blockig select

### ISSUE THREAD

**Issue by ahromyak** [Dimox/jQueryFormStyler#117]
I have issue when on mobiles, selects are not working because of that line  if (iOS) return;. I have checked your examples and if you will emulate iphone it will not work also.
p.s. on real iphone i have checked it also.
please let me know if you have workaround to this.
thanx
fitline83@gmail.com

**Comment by Dimox** [comment]
iOS shows native dropdown list and I don't how to hide it, that's why I have added this line:

```
if (iOS) return;

**Comment by vytya** [comment]
хром последний в эмуляции ифон не срабатывает вообще никакой селект, ни нативный, ни стайлеровский. айфоны тож. 

убрал из джса ретурн этот, стал показываться стайлеровский.
