### ISSUE TITLE
Поддержка многоязычности

### ISSUE THREAD

**Issue by ArmGono** [Dimox/jQueryFormStyler#118]
Привет. Хотел предложить реализовать многоязычность в плагине, т.к. при использовании на многоязычных проектах возникают сложности с переводами. Приходится для каждой формы писать "костыли". Я на днях постараюсь накидать решение этой задачи.

**Comment by yunusga** [comment]
@ArmGono, отличная идея, вот тут https://github.com/nazar-pc/PickMeUp#localization хороший пример локализации. Хотя можно и обсудить тут это со всеми

**Comment by ArmGono** [comment]
Что-то вроде этого получается
[patch.txt](https://github.com/Dimox/jQueryFormStyler/files/659758/patch.txt)

**Comment by yunusga** [comment]
@Dimox, где же ты?!
