### ISSUE TITLE
The "click" event isn't triggered for checkbox/radio button

### ISSUE THREAD

**Issue by aik099** [Dimox/jQueryFormStyler#120]
For real checkbox/radio button 2 events are triggered:

* the `change` when checkbox/radio button value was actually changed
* the `click` when click on the checkbox/radio button happened

The jQueryFormStyler isn't triggering the `click` event to emulate behavior of real checkbox/radio button.

The use case for `click` event in case of radio buttons is to monitor user clicks and always react on them regardless if a click caused radio button to be selected or not.

**Comment by Dimox** [comment]
Почему не по-русски?

**Comment by aik099** [comment]
Because I don't want to restrict discussion to Russian speaking contributors. If posting issues/PR in Russian is a requirement, then please indicate that in `CONTRIBUTING.md` file, where all contributor guidelines are located.

**Comment by pafnuty** [comment]
@aik099 why you use this plugin for checkbox and radiobuttons? You can make them with CSS 😄

**Comment by aik099** [comment]
Last time I've checked attempt to apply styles directly on `<input type="checkbox"/>` haven't produced consistent cross-browser and cross-os results.

**Comment by pafnuty** [comment]
for example: http://codepen.io/pafnuty/pen/PpzbQw

**Comment by aik099** [comment]
Wow, that's cool.

Not sure about browser compatibility, but one thing I've noticed is when clicking on 2nd checkbox label it blinks each time. Tried on macOS in Google Chrome.

**Comment by pafnuty** [comment]
it just examle. You can find more examples like [this good variant](http://dimox.name/examples/checkboxes-radio-buttons-using-css.html).
Compatibility depends on the support of specific features in browsers, but all browsers, the percentage of use is greater than 1% was support all modern properties.

**Comment by gmelikov** [comment]
Согласен, вообще это большая проблема, многие плагины подписываются на событие click, а так как этот плагин при клике вызывает `e.preventDefault();`, то событие клика не отрабатывается. Думаю, что это критично, привязаться на клик - целая проблема. К примеру, приходится переписывать CMSки.

@Dimox, если готовы принять PR, могу подготовить пример.

@aik099 agree with you, english is a mandatory now.

**Comment by pafnuty** [comment]
@gmelikov Мне кажется не стоит идти на поводу у тех, кто вешает клик на чекбокс, а для таких случаев использовать CSS для оформления этих чекбоксов. Если нет доступа к html чекбокса - можно добавить немного js и завернуть чекбокс в нужный код.

> Согласен, вообще это большая проблема, многие плагины подписываются на событие click, 

А можно несколько примеров?

**Comment by gmelikov** [comment]
@pafnuty мы говорим о плагине, который переопределяет стандартные события. Не стоит идти на поводу у стандартных событий, определённых [W3C](https://www.w3.org/TR/DOM-Level-3-Events/#event-type-click)? Я не против CSS, но почему бы не решить проблему и здесь?

> А можно несколько примеров?

Битрикс.

**Comment by pafnuty** [comment]
@gmelikov Я не против решения, просто не понимаю смысла исправлять то, что не несёт реальной проблемы, но при этом исправление может потенциально принести больше проблем, чем сейчас.
В любом случае решать должен @Dimox, в PR никто не мешает отправить в любой момент.

> Битрикс.

за почти 5 лет разработки разных сайтов на битриксе (слава богу это время осталось в прошлом) ниразу не встречал этой проблемы. Разве только умный фильтр, но там вообще js [для чекбоксов не нужен](https://avant-bt.ru/catalog/moyki_iz_iskusstvennogo_kamnya/?set_filter=y&arrFilter_19_2226203566=Y&arrFilter_19_498629140=Y&arrFilter_584_3501491535=Y&arrFilter_P10_MAX=11996) к тому же битрикс сложно отнести к плагинам :smile:

**Comment by gmelikov** [comment]
> но при этом исправление может потенциально принести больше проблем, чем сейчас

Какие проблемы могут быть в обеспечении соответствия стандартам? Тут скорее вопрос на сколько широк круг желающих.

> Разве только умный фильтр, но там вообще js для чекбоксов не нужен

именно с ним, js используется для отображения блока "Выбрано: XX" при смене фильтра.

> к тому же битрикс сложно отнести к плагинам

а что мешает js коду того же умного фильтра быть плагином? =)

**Comment by Dimox** [comment]
> @Dimox, если готовы принять PR, могу подготовить пример.

Делайте.

**Comment by pafnuty** [comment]
> Какие проблемы могут быть в обеспечении соответствия стандартам?

А где там упоминается о том, что нельзя запрещать стандартное действие? :)

С умным фильтром я показал пример (один из многих), где js не нужен для полноценной стилизации чекбоксов, и вроде там всё до сих ор работает как положено.
Я понимаю увлечение js`ом, но применительно к радиокнопкам и чекбоксам это излишне, имхо. Лишние обработчики, лишний код, лишние проблемы, он действительно необходимо? 

> а что мешает js коду того же умного фильтра быть плагином? =)

Особая битрикс-атмосфера из дичайшей смеси разметки, php и js в одном файле :smile: но не мне вам об этом рассказывать :)

**Comment by D0Gmatist** [comment]
битрикс... зло

**Comment by gmelikov** [comment]
@pafnuty я понимаю вас и полностью согласен, другой вопрос что мы обсуждаем это в issue данного плагина=) Конкретно мой случай - проект с уже внедрённым плагином, мне быстрее пока оставить его, чем всё переписать.

**Comment by Dimox** [comment]
Сделано - [2.0.0](https://github.com/Dimox/jQueryFormStyler/blob/master/CHANGELOG.md#История-изменений).
