### ISSUE TITLE
Опция для отключения стилей

### ISSUE THREAD

**Issue by Gal0n** [Dimox/jQueryFormStyler#121]
После инициализации скрипта к созданным элементам применяются инлайновые стили (например, `display: inline-block; position: relative `). Часто необходимо переопределить их для реализации задуманного дизайна, что приходится делать при помощи `!important`, что, в свою очередь, добавляет определенные неудобства в дальнейшем каскадировании стилей. Очень хотелось бы либо опцию в настройках, чтобы можно было отключить стили, добавляемые скриптом, либо эти инлайновые стили сразу нужно вынести в css, а не добавлять скриптом. Было бы замечательно.

**Comment by Dimox** [comment]
Делать опцией, на мой взгляд, некрасиво. Правильнее было бы вынести стили в css-файл.

Однако, после этого предполагаю, что появится множество сообщений в стиле "плагин не работает", "всё разъехалось" от тех, кто не подключит обязательные стили. Да даже после обновления на новую версию с этим изменением всех будет ожидать неприятный сюрприз, ведь они не знают, что теперь есть отдельные обязательные стили.

**Comment by Gal0n** [comment]
Некрасивое решение - тоже решение, и многим очень бы помогло.  Тем более если вариант с вынесенными стилями отпадает. Подумайте над этим, пожалуйста.

**Comment by pafnuty** [comment]
> Да даже после обновления на новую версию с этим изменением всех будет ожидать неприятный сюрприз, ведь они не знают, что теперь есть отдельные обязательные стили.

Такие проблемы решаются с помощью изменения мажорной версии. Например 2.0.0

**Comment by Dimox** [comment]
`Такие проблемы решаются с помощью изменения мажорной версии. Например 2.0.0`

Да, уже решил, что так и сделаю.

**Comment by Dimox** [comment]
Сделано - [2.0.0](https://github.com/Dimox/jQueryFormStyler/blob/master/CHANGELOG.md#История-изменений).
