### ISSUE TITLE
Баги с selectVisibleOptions

### ISSUE THREAD

**Issue by Gal0n** [Dimox/jQueryFormStyler#123]
Критично:
Если задать selectSmartPositioning значения `false` или `-1`, то `selectVisibleOptions` перестает работать (**max-height** выпадающему списку не задается вообще). 

Некритично:
Если задан selectPlaceholder и не указан **min-height** для `.jq-selectbox li `, то при включенной опции `selectVisibleOptions ` **max-height** считается неверно, так как при расчете берется высота первого элемента списка, который пустой, а значит, ниже соседних элементов. Если сказать более глобально, то  `selectVisibleOptions` считается неверно, если пункты в выпадающем списке разной высоты.  

Вероятно, нужно улучшить алгоритм расчета **max-height**. Ну или хотя бы указать в описании плагина ограничения на использование данной опции c учетом написанного выше. А то вебмастерам порой трудно понять, почему плагин работает не так, как ожидалось

**Comment by pafnuty** [comment]
@Gal0n Пробовали этот плагин: https://github.com/ange007/JQueryFormStyler-Modern ?

**Comment by Dimox** [comment]
> Если задать selectSmartPositioning значения false или -1, то selectVisibleOptions перестает работать (max-height выпадающему списку не задается вообще).

Проверил сейчас - перестает работать только при значении `-1`. При `false` работает.

**Comment by Gal0n** [comment]
@Dimox Да, извиняюсь, с `false` работает. Проблема c `-1`.

@pafnuty Нет, не пробовал. Вынос стилей из скрипта там, смотрю, сделали, что воодушевляет.

**Comment by Dimox** [comment]
Исправлено в новой версии.
