### ISSUE TITLE
Не открывается select на iOS

### ISSUE THREAD

**Issue by Neolot** [Dimox/jQueryFormStyler#124]
Привет!
Странный баг, стилизованный select не открывается на iOS.
Тестировал на Windows и на Маке в Chrome и Safari в консоли разработчика. На реальном устройстве не могу проверить.
На Android бага нет.

**Comment by pafnuty** [comment]
Так и должно быть т.к. iOS не позволяет скрывать дефолтный селект, пока этой проблемы нет :(

**Comment by Dimox** [comment]
На реальном устройстве открывается нативный селект.
