### ISSUE TITLE
.less, .scss формат 

### ISSUE THREAD

**Issue by geekofcola** [Dimox/jQueryFormStyler#126]
Было бы удобно добавить эти форматы.
Если нету возможности добавить, могу допилить по свободе.

**Comment by pafnuty** [comment]
Уже было. 
https://github.com/Dimox/jQueryFormStyler/issues/15
https://github.com/Dimox/jQueryFormStyler/pull/39
Если хочется scss - вам [сюда](https://github.com/ange007/JQueryFormStyler-Modern/tree/dev)

**Comment by geekofcola** [comment]
спасибо:)
