### ISSUE TITLE
gulp-bower не находит файлы

### ISSUE THREAD

**Issue by archaron** [Dimox/jQueryFormStyler#134]
Пытался подключить в сборку через gulp-bower-main-files, но gulp не видит styler. Изучил, скорее всего дело в этом:

```
"main": [
		"jquery.formstyler.min.js",
		"jquery.formstyler.css"
	],
```

При этом, bower ругается на то, что нельзя включать MIN файлы в main секцию.

> invalid-meta The "main" field cannot contain minified files

Сделал override, с которым работает и не ругается:
```
"jquery.form-styler": {
      "main": [
        "./dist/jquery.formstyler.js",
        "./dist/jquery.formstyler.css"
      ]
    }

```
Может быть я как-то не так пытаюсь его подключить?

**Comment by Dimox** [comment]
Я bower никогда не использовал, поэтому не знаю, как правильно. Пути до файлов в последней версии поменялись, видимо, в этом причина.
