### ISSUE TITLE
require не работает

### ISSUE THREAD

**Issue by versh23** [Dimox/jQueryFormStyler#136]
Привет. не могу подключить плагин используя require.
Делаю так
```
var $ = jQuery = window.jQuery = window.$ = require('jquery');
require('jquery.formstyler');
(function($) {
    $(function() {

    $('input, select').styler();

    });
})(jQuery);
```

получаю ошибку
`Uncaught TypeError: $(...).styler is not a function`

**Comment by Dimox** [comment]
К сожалению, я в этом не разбираюсь.

**Comment by Dimox** [comment]
Исправлено в 2.0.1.

**Comment by versh23** [comment]
@Dimox Класс, но почему то в npm еще 2.0.0 версия
https://www.npmjs.com/package/jquery-form-styler

Может какой то триггер на релиз не сработал? Сделайте релиз, пожалуйста

**Comment by Dimox** [comment]
Постоянно про это забываю. Только что опубликовал.
