### ISSUE TITLE
Input[type=number] doen't handles "input" jQuery event on spin click

### ISSUE THREAD

**Issue by holdmann** [Dimox/jQueryFormStyler#139]
now you can use timer, for trigger manually:

`
$(document).ready(function() {
        // remember current values.
        var prevValues = [];

        $('input[type="number"]').each(function (index, el) {
            prevValues[index] = $(el).val();

        });

        var pollInterval = setInterval(function() {

            var curValues = [];

            $('input[type="number"]').each(function (index, el) {

                if ($(el).val() != prevValues[index]) {
                    $(this).trigger('input');
                    curValues[index] = $(el).val();
                }

            });

        }, 100);
    });
`

**Comment by Dimox** [comment]
Fixed in 2.0.1.
