### ISSUE TITLE
Добавьте теги 2.0.1 и 2.0.2

### ISSUE THREAD

**Issue by holdmann** [Dimox/jQueryFormStyler#143]
Добавьте теги 2.0.1 и 2.0.2, bower не может вытянуть последнюю версию, берет по тегу 2.0.0

**Comment by Dimox** [comment]
Добавить куда? Я в этом не разбираюсь. В bower.json указана версия 2.0.2.

**Comment by holdmann** [comment]
Вот сюда - http://joxi.ru/krDLKPnfEkO1er

**Comment by Dimox** [comment]
Добавил только 2.0.2. Постоянно забываю делать релизы.
