### ISSUE TITLE
Event handler-ы

### ISSUE THREAD

**Issue by thehappycoder** [Dimox/jQueryFormStyler#23]
Не хватает того, чтобы плагин посылал event после вызова:
checkbox.addClass('checked')
и
checkbox.removeClass('checked')

Это нужно для того, чтобы показывать галку плавно.

Пока реализовал прямо в jquery.formstyler.js такой хак:
function toggleChecked(checkbox, checked) {
          if (checked) {
            checkbox.children('.jq-checkbox__div').animate({'opacity': 1});
            checkbox.addClass('checked');
          } else {
            checkbox.children('.jq-checkbox__div').animate({'opacity': 0});
            checkbox.removeClass('checked');
          }
        }

Я не нашёл грамотного решения как это сделать вне этого файла. Ведь слушать изменения класса элемента через javascript не получится во всех нужных браузерах?

**Comment by NesCafe62** [comment]
можно еще попробовать через css анимацию реализовать, у меня в проекте например многие неосновные анимационные эффекты через css анимируются, это и удобнее и на скрипты меньше нагрузка (плюс они поддерживают аппаратное ускорение)
