### ISSUE TITLE
The "blur" event fired prematurely for "select"

### ISSUE THREAD

**Issue by aik099** [Dimox/jQueryFormStyler#36]
I have styled SELECT and a "blur" event handler set to validate it's value.

Here is what happens:
1. I click on styled DIV
2. UI with options opens
3. I select an option (click on LI)
4. __blur event is fired on actual SELECT control__
5. __inside blur event handler the select.value has previous value__
6. the UL option list is closed

What should happen (if we mimic real SELECT behavior):
1. I click on styled DIV
2. UI with options opens
3. I select an option (click on LI)
4. the UL option list is closed
5. __blur event is fired on actual SELECT control__
6. __inside blur event handler the select.value has new value__

**Comment by NesCafe62** [comment]
Проблема решается проще, нужно вместо blur использовать change

**Comment by aik099** [comment]
It would work yes, but create different UX at the end. The `change` event is fired immediately after value is changed for `SELECT`, but for textboxes it's only fired after `blur` happened. That's why I want to keep consistent event handling across different form controls by using `blur`.

**Comment by NesCafe62** [comment]
Если есть и textbox-ы и select-ы, тогда вы правы. Я бы как временное решение создал обработчик и вызывал бы его через trigger для textbox-ов и всех остальных по событию blur а для select-ов по change. А так конечно правильнее бы было починить последовательность вызова событий при стандартном поведении.

**Comment by slavent** [comment]
"Skype не люблю, да и вряд ли он что-то изменит, т.к. у меня мало опыта в JavaScript, к сожалению. И у меня нет начальника, и я вроде как никому ничего не обязан."

Вот это вообще позабавило.
