### ISSUE TITLE
Утечка памяти в $(document).click()

### ISSUE THREAD

**Issue by generalov** [Dimox/jQueryFormStyler#54]
https://github.com/Dimox/jQueryFormStyler/blob/master/jquery.formstyler.js#L655
Для каждого элемента 'select' на странице `styler` регистрирует обработчик события 'click' в `document`.
 
Есть две проблемы:
1. Если на странице элементов 'select' достаточно много (на практике встретилась страница где их ~900), браузер начинает заметно тормозить при каждом клике.
2. После удаления элементов 'select' со страницы, обработчики остаются в памяти. Это критично для SPA, где элементы добавляются и удаляются динамически.

**Comment by Dimox** [comment]
Наконец-то созрел для решения этой проблемы. Переделал структуру плагина (пока еще тестирую, в паблик не выложен). Теперь, как вы и писали, опции хранятся в `.data` и их можно считать с любого стилизованного элемента.

Задействовал вашу функцию [onDocumentClick](https://github.com/generalov/jQueryFormStyler/commit/de666dc6411eb29b504e038d4a49fe681f7e3b5b). Получаются такие результаты (стилизуемых элементов примерно 20 штук):

```
$._data(document, "events" );
undefined // количество обработчиков до вызова styler

$('input, select').styler(); // вызывали
$._data(document, "events" );
Object {click: Array[1]} // количество обработчиков после применения styler

$('input, select').remove(); // удалили элементы форм
$._data(document, "events" );
Object {click: Array[1]} // количество обработчиков после удаления
```

Можно ли теперь считать, что проблема с утечкой устранена?

**Comment by generalov** [comment]
> пока еще тестирую, в паблик не выложен
нет))

**Comment by Dimox** [comment]
Не понял ответа.

**Comment by generalov** [comment]
я не могу проверить решен-ли вопрос, пока кода нет в паблике.

**Comment by Dimox** [comment]
Пожалуйста - https://dl.dropboxusercontent.com/u/7312900/jquery.formstyler.js

**Comment by Dimox** [comment]
@generalov, потестировали? Все ли в порядке?
