### ISSUE TITLE
Проблема со selectSmartPositioning и overflow: hidden

### ISSUE THREAD

**Issue by Zoxon** [Dimox/jQueryFormStyler#64]
Проблема в том что смещение считается от края экрана, но если селект положить в блок с overflow: hidden; SmartPositioning отрабатывает неверно.

![2014-11-10 14-05-07](https://cloud.githubusercontent.com/assets/3866196/4972792/45b59646-68b1-11e4-8879-3824351213de.png)

Возможно стоит проверять не только смещение от окна но и до ближайшего елемента с overflow: hidden?
Или какое либо другое решение?

Спасибо.

**Comment by pafnuty** [comment]
@Zoxon попробуйте [magnificpopup](https://github.com/dimsemenov/Magnific-Popup) я в своё время перешел на этот плагин, очень доволен, плагин гибок и не привязан к какой то определённой структуре html.
