### ISSUE TITLE
build system

### ISSUE THREAD

**Issue by talgautb** [Dimox/jQueryFormStyler#66]
почему до сих пор нет gulpjs или аналога ?
Каждый раз ручками всё собирается ?
Можно добавить ко всему:
- css препроцессоры
- автопрефиксер (чтобы не следить за всеми префиксами, каждый может настроить для себя какие необходимо)

готов помочь по всем вопросам, описанным выше)

**Comment by unclechu** [comment]
Мейнтейнер скорее всего просто об этом даже не слышал. Не так давно с трудом протолкнули UMD обёртку.

**Comment by Dimox** [comment]
Я с такими вещами не дружу, не мое это.

> Каждый раз ручками всё собирается ?

А чего там собирать-то? Только JS-файл минимизировать и все.

**Comment by talgautb** [comment]
@unclechu ok ) тогда надо делать форк)
@Dimox автоматизация рутины :)

**Comment by unclechu** [comment]
@talgautb тогда для форка нужно изменённое имя проекта, чтобы не создать путаницы исходного проекта с форком. Я если чё поконтрибьючу :)
