### ISSUE TITLE
Названия классов

### ISSUE THREAD

**Issue by talgautb** [Dimox/jQueryFormStyler#67]
Как насчет добавить в настройки изменения имен для классов ?
Например, мы используем методологию и использовать стили в текущем варианте нам не удобно, да и в целом, могут классы пересекаться

**Comment by Dimox** [comment]
Их слишком много в плагине, чтобы делать настраиваемыми.

**Comment by talgautb** [comment]
@Dimox как вариант можно просто добавлять в текущую структуру по необходимые классы, чтобы не изменять текущие классы
могу что-нибудь сделать как пример, там посмотрим как лучше сделать
