### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by talgautb** [Dimox/jQueryFormStyler#68]
А можно как-нибудь убрать инлайновый `z-index:100;` для `select`?
постоянно с ними борюсь :)

**Comment by Dimox** [comment]
Ты можешь только уменьшить индекс через опцию. А убрать нельзя, т.к. это нужно для корректной работы.

**Comment by talgautb** [comment]
о есть найстройки :) добавить бы в Readme, а то я, например, не знал)

**Comment by Dimox** [comment]
С добрым утром, называется =) [Тут](http://dimox.name/jquery-form-styler/) же всё написано.

**Comment by talgautb** [comment]
:) спасибо)
