### ISSUE TITLE
Не видит теги внутри селекта

### ISSUE THREAD

**Issue by serjyamp** [Dimox/jQueryFormStyler#69]
Добавляю в тег option тег Fontawesome <code>< i class="fa fa-rub"></ i></code> и плагин его игнорирует, не выводит вообще иконку. Как исправить?

**Comment by vaeum** [comment]
внутри option ничего кроме текста не вставляйте, а просто добавьте класс и этому классу задайте стиль

**Comment by pafnuty** [comment]
А разве в option допускается использование html?

**Comment by serjyamp** [comment]
"внутри option ничего кроме текста не вставляйте, а просто добавьте класс и этому классу задайте стиль"

что имеется в виду?
