### ISSUE TITLE
Плагина нет в bower

### ISSUE THREAD

**Issue by mogafk** [Dimox/jQueryFormStyler#74]
собсна

**Comment by Dimox** [comment]
Не знаю, в чем причина. Файл bower.json заполнялся в соответствии с [примером](https://github.com/Dimox/jQueryFormStyler/issues/31).

**Comment by mogafk** [comment]
Блин. Оказывается пакет есть, но название jquery.form-styler это неожиданно.

**Comment by mogafk** [comment]
http://bower.io/search/ - не находил, но если ввести bower search dimox, то находил по ссылке на репозиторий.

**Comment by mogafk** [comment]
Было два комента, но с кривой формулировкой. Удалю их перефразирую:
Когда я ищу пакет через [bower.io/search](http://bower.io/search/), то ожидаю найти его по имени в bower.json(Dimox/jQueryFormStyler), но у тебя он зарегестрирован как jquery.form-styler. Отсюда возникла моя путаница. Я извиняюсь это проблема недостатка моего опыта.
Пакет можно быстро найти, если искать через cli как ** bower search **. 
Но в целом не мешало бы куда-нибудь(readme, homepage) добавить название пакета в bower.
Так же можно было бы убрать из bower пакета файл .gitignore и директорию demo. Для этого можно просто написать   "ignore": [
	"**/.*",
	"demo"
  ]
Прости еще раз за такой бессмысленный иссай.
