### ISSUE TITLE
body on click problem

### ISSUE THREAD

**Issue by soltx** [Dimox/jQueryFormStyler#75]
<pre>
$(‘body’).on(‘click’, ‘.jq-checkbox’, function(){
// not working
})
</pre>

<pre>
$(‘.jq-checkbox’).on(‘click’,  function(){
// working
})
</pre>
Hi! Who knows about how to Fix ?

**Comment by a-t** [comment]
Hi. It's fixed [here](https://github.com/a-t/jQueryFormStyler/commit/a5f3a3a25c78aec3ffa6802cebfdf3e1a7045930). You may freely use this version of the plugin or wait for the changes to be merged into the main repository.

**Comment by Sky161** [comment]
Проблема с radio кнопками. Никак не реагируют на клик. Пробывал так:
$('body').on('click', '.jq-radio',  function(){
			alert('1');
		});
и так:
$('jq-radio').on('click',  function(){
			alert('1');
		});

**Comment by Dimox** [comment]
Исправлено в версии 1.7.3.
