### ISSUE TITLE
input type="number"

### ISSUE THREAD

**Issue by bigvax** [Dimox/jQueryFormStyler#79]
Во первых - большое спасибо за плагин.
И еще есть вопрос: планируется-ли стилизовать input с типом "number" ?
А то он во всех браузерах выглядит сильно по разному... :(

Это сейчас довольно «модное» поле для выбора кол-ва товаров во всяких магазинах и каталогах, и его использование будет расти.

Кроме того, (но это, конечно менее приоритетно), зачастую (в зависимости от дизайна) бывает нужны разные виды этого контрола - иногда похожий на дефолтный вид в браузерах - т.е. стрелочки вверх/вниз в самом поле или рядом с ним, а иногда желательны горизонтальные стрелочки (кнопки) вокруг поля. 

В одном из своих проектов, я это делал примерно как на картинке ниже. 
Изображения нигде не используются - все сделана стилями и custom font. 
Соответственно, если, что-либо подобное можно было-бы сделать в плагине - думаю, что многие были-бы благодарны.
При необходимости, могу поделится своими наработками по этому вопросу (правда не знаю, впишутся-ли они в общий стиль плагина);

![inumber](https://cloud.githubusercontent.com/assets/284112/8636065/2ff98dda-2855-11e5-81ea-ae705224c80f.jpg)

**Comment by Dimox** [comment]
Я задумывался об этом, но поддержку стилизации данного элемента еще никто не просил за такое продолжительно время существования плагина.

Реализовать это не сложно, поэтому, наверное, сделаю.

**Comment by Dimox** [comment]
Добавил. Смотрите последнюю версию.

**Comment by bigvax** [comment]
Отлично!
Спасибо большое!
