### ISSUE TITLE
Download plugin to npm system

### ISSUE THREAD

**Issue by CustomButtons** [Dimox/jQueryFormStyler#80]
Please register plugin on https://www.npmjs.com/
for easy install, like `npm install jQueryFormStyler --save-dev`

**Comment by Dimox** [comment]
Я не знаю, как это сделать.

**Comment by CustomButtons** [comment]
And register to http://bower.io/ too
for easy install, like `bower install jQueryFormStyler --save-dev`
Instructions https://docs.npmjs.com/getting-started/publishing-npm-packages and http://bower.io/docs/creating-packages/

**Comment by Dimox** [comment]
В bower он уже есть - http://bower.io/search/?q=form-styler

**Comment by Dimox** [comment]
В npmjs.com добавить не могу, т.к. они не скрывают e-mail пользователя.
