### ISSUE TITLE
Возможность открытия селекта по событию.

### ISSUE THREAD

**Issue by pafnuty** [Dimox/jQueryFormStyler#83]
Хотел сегодня реализовать открытие селекта при нажатии на кнопку (физически это спан), для чего попробовал в консольке код:
`$('#city-styler .jq-selectbox__select').trigger('click');`? как и ожидалось селект открылся, однако, при пользовательском действии такой трюк не сработал:
```javascript
$(document).on('click', '.city', function () {
	$('#city-styler .jq-selectbox__select').trigger('click');
});
```

Тоже самое происходит с [демкой](http://dimox.github.io/jQueryFormStyler/demo/#select):
`$('.width-auto .jq-selectbox__select').trigger('click');` так в консоли работает, а вот так (прямо в консоль писал) нет:
```
$(document).on('click', '.add-select', function () {
	$('.width-auto .jq-selectbox__select').trigger('click');
	console.log('кнопка действительно нажата');
});
```

Призняться я теряюсь в догадках.

**Comment by Dimox** [comment]
Могу предположить, что это связано с проблемой, решение которой предлагается [здесь](https://github.com/Dimox/jQueryFormStyler/pull/82).

**Comment by pafnuty** [comment]
@Dimox да, похоже на то, по крайней мере есть на что ориентироваться теперь, попробую починить.

**Comment by Dimox** [comment]
Добрался наконец до тестирования всего этого дела. Ситуация следующая.

С чекбоксами и радиокнопками наблюдается точно такая же проблема (т.е. при `$(document).on('click'` ничего не происходит). Правки, которые предложил @a-t, исправляют это, однако проблема с селектом все так же остается.

Обнаружил, что твой код начинает работать, если закомментировать в плагине этот код:

```JavaScript
// прячем выпадающий список при клике за пределами селекта
if (!onDocumentClick.registered) {
	$(document).on('click', onDocumentClick);
	onDocumentClick.registered = true;
}
```

Осталось разобраться, как сделать, чтобы работало и то, и другое одновременно.

**Comment by Dimox** [comment]
Так-с, интересно получается. Когда запускаем твой код, селект на самом деле открывается, но, поскольку дальше срабатывает функция "прячем выпадающий список при клике за пределами селекта", то селект сразу же и закрывается =)

Нужно придумать, как это дело обойти.

**Comment by Dimox** [comment]
Ура! Решение оказалось очень простым:

```JavaScript
$(document).on('click', '.add-select', function (e) {
	e.stopPropagation();
	$('.width-auto .jq-selectbox__select').trigger('click');
	console.log('кнопка действительно нажата');
});
```

**Comment by pafnuty** [comment]
@Dimox спасибо!
Ещё и на CDN наконец то приняли плагин. Класс!

**Comment by Dimox** [comment]
Пожалуйста.

Так он уже там давным-давно =) Архив с версии 1.5.4. Доброе утро, страна =)

**Comment by pafnuty** [comment]
:smile: бывает
