### ISSUE TITLE
Ошибки валидации при использовании плейсхолдеров в селектах

### ISSUE THREAD

**Issue by Zoxon** [Dimox/jQueryFormStyler#85]
<select data-placeholder="-- Выберите --">
	<option></option>
	<option>Пункт 1</option>
	<option>Пункт 2</option>
	<option>Пункт 3</option>
	<option>Пункт 4</option>
	<option>Пункт 5</option>
</select>

Ругается на пустой option

**Comment by Dimox** [comment]
Достаточно добавить параметр `label` с не пустым значением:

```HTML
<option label="-"></option>
```
