### ISSUE TITLE
Возвращаемое значение

### ISSUE THREAD

**Issue by a-t** [Dimox/jQueryFormStyler#87]
Почему плагин возвращает обещание (promise), а не jQuery-коллекцию, как это обычно делается? Получается дублирование функциональности (ведь есть опция `onFormStyled`), неожиданное поведение (большинство jQuery-плагинов возвращают коллекцию), а также некоторое неудобство из-за того, что после инициализации плагина невозможно продолжать цепочку вызовов.

До [версии 1.4.9](https://github.com/Dimox/jQueryFormStyler/commit/0c07e644f95b0a57130fca0b176335f546c7847e#diff-6827f9431e91cf63de501b73db4046c1R802) возвращался-таки jQuery-объект. В [чендж-логе](https://github.com/Dimox/jQueryFormStyler/blob/572d18d91f96e3fe40a0b7cd91310a8d2884ddc1/CHANGELOG.md#149-18032014) упоминания о смене возвращаемого значения нет. Смею предположить, что это баг :)

**Comment by Dimox** [comment]
Не знаю, что такое jQuery-коллекция. promise нужен для того, чтобы срабатывал колбек onFormStyled.

**Comment by a-t** [comment]
jQuery-коллекция — объект, возвращаемый функцией [`jQuery()`](http://api.jquery.com/jQuery/) (она же `$()`). Например, `$("input, select")` — это коллекция. Причина создания обещания вопросов не вызывает. Я говорю о том, что promise (в jQuery это называется [`Deferred`](http://api.jquery.com/jQuery.Deferred/)) *возвращается* при вызове плагина *вместо* коллекции.
```javascript
var foo = $("input, select").styler(); // теперь foo — это объект jQuery.Deferred
```
Поэтому подобные цепочки невозможны:
```javascript
$("input, select").styler().addClass("styled");
```

**Comment by Dimox** [comment]
Я в таких тонкостях не разбираюсь =(

**Comment by a-t** [comment]
Хорошо :) Попробую попроще.

jQuery позволяет писать так:
```javascript
$("input").css( ... ).after( ... ).prependTo( ... ) // и т. д.
```
По вашему мнению, как автора плагина, должна ли быть возможность включать вызовы `.styler()` в такие цепочки? Или же такая возможность *нарочно* исключена в релизе 1.4.9 ради каких-то целей?

**Comment by Dimox** [comment]
Про цепочки я понял, и логично, что с плагином это должно работать. Но я не делал ничего намеренно, чтобы это перестало работать. И не имею представления, из-за чего это поломалось, если до версии 1.4.9 работало. Вот про это я и сказал: "в таких тонкостях не разбираюсь".

**Comment by a-t** [comment]
`.promise()`, в отличие от `.each()`, прерывает цепочку, т. к. возвращает `jQuery.Deferred`, а не объект `jQuery`, поэтому надо просто явно вернуть `this`.

**Comment by Dimox** [comment]
Окей. Спасибо!
