### ISSUE TITLE
Publish on NPM?

### ISSUE THREAD

**Issue by faergeek** [Dimox/jQueryFormStyler#90]
Why don't you publish it on npm?

**Comment by faergeek** [comment]
Sorry, found issue #80.
What if I publish it for you?

**Comment by Dimox** [comment]
Я уже там ответил, почему не добавляю.

**Comment by faergeek** [comment]
Ок, что если я добавлю со своего аккаунта?

**Comment by faergeek** [comment]
или можно хотя бы `package.json` добавить, чтоб с гитхаба ставить?

**Comment by Dimox** [comment]
> Ок, что если я добавлю со своего аккаунта?

Разработчик же я, а не ты =)

> или можно хотя бы package.json добавить, чтоб с гитхаба ставить?

Можно, только я не знаю, что в нем должно быть.

**Comment by faergeek** [comment]
Я могу указать тебя как разработчика без почты, а указать ссылку на аккаунт на гитхабе, а себя указать как мэйнтейнера пакета уже с почтой и всеми делами.

**Comment by Dimox** [comment]
Так согласен.
