### ISSUE TITLE
React version?

### ISSUE THREAD

**Issue by faergeek** [Dimox/jQueryFormStyler#91]
Что если я сделаю обёртку для реакта, использующую этот плагин, ты примешь Pull Request?

**Comment by Dimox** [comment]
Что такое обертка?

**Comment by faergeek** [comment]
Суть в том, что реакт обычно контроллирует DOM, а этот плагин соответственно меняет его.
Так что чтобы использовать этот плагин с реактом, нужно его завернуть в компонент и обрабатывать все шероховатости, связанные с модификациями DOM.

То есть буквально нужно написать пару компонентов, которые оборачивают кастомизируемые контролы.

**Comment by faergeek** [comment]
Хотя лучше наверное отдельным пакетом это сделать.
