### ISSUE TITLE
option value

### ISSUE THREAD

**Issue by ChumakovAnton** [Dimox/jQueryFormStyler#96]
Как найти value выбранного option в селекте?
Искать по тексту?

**Comment by vaeum** [comment]
$("select").val()

**Comment by ChumakovAnton** [comment]
Я имею в виду, в контексте этого плагина. Этот плагин оборачивает select стилизованными блоками. И пользователь работает с этими блоками, а не с селектом. Соответственно когда происходит выбор какого-то пункта, добавляется класс "selected sel" этому пункту, но в первоначальном элементе select выбора не происходит и val() ничего не возвращает.

**Comment by vaeum** [comment]
вы пытаетесь получить value у diva-обертки
например вы инициальзируете select с классом test
и value получить 
$("select.test").val()
просто 
$(".test").val()
неполучиться

**Comment by ChumakovAnton** [comment]
Большое спасибо! Все верно, копирует класс select в div. Не углядел)
