### ISSUE TITLE
data-placeholder как обнулить select?

### ISSUE THREAD

**Issue by Satif** [Dimox/jQueryFormStyler#97]
Есть проблема. Мне надо при клике на кнопку обнулять выбранный селект. Т.е. если до этого я выбрал опцию 2, то после клика должен снова показываться текст с data-placeholder

**Comment by pafnuty** [comment]
```js
$('select').val('').trigger('change');
```
Пробовали?

**Comment by Satif** [comment]
Да так норм. Спасибо большое!
