### ISSUE TITLE
Feature for selectedIndex = -1

### ISSUE THREAD

**Issue by westyby** [Dimox/jQueryFormStyler#98]
Привет. Стилизуем уже готовый back-end. Заново переписывать его уже никто не будет, поэтому возникла потребность модифицировать плагин. Я понимаю, что есть триггеры 'change', 'refresh', но чтоб их вызвать, надо очень много всего менять.
При загрузке страницы есть select:
```
<select id="select">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
    </select>
```
Далее через JS убирают выбранный пункт . Отображается select в котором не выбран ни один из пунктов https://s.mail.ru/4L9KUva9Zy8H/img-2015-11-19-15-40-19.png
```
document.getElementById('select').selectedIndex = -1
```

Потом запускается инициализация formstyler и опять появляется выбранный пункт https://s.mail.ru/3eZj1eXJe12C/img-2015-11-19-15-42-57.png 
```
$('select').styler();
```
Это поведение неверно. Должен быть пустой select  https://s.mail.ru/5PHacVj5QAsP/img-2015-11-19-15-47-04.png

При выборе одного из пунктов в селекте - уже нормально должно все выбираться. 
Дописал чтоб плагин проверял, какое значение выбранного элемента, и в зависимости от этого либо ставил значение, либо нет
Пример в архиве https://cloud.mail.ru/public/C7WB/xt1i5sYsP

**Comment by pafnuty** [comment]
Попробуйте вставить в начало списка пустой `<option></option>`

**Comment by westyby** [comment]
Обычно так и делал, но тут в код проекта лучше не лезть
