### ISSUE TITLE
Feature for input[onclick]

### ISSUE THREAD

**Issue by westyby** [Dimox/jQueryFormStyler#99]
В библиотеке есть обработчик клика на label. Кликнули по label - выполнилось то, что на псевдочекбоксе https://s.mail.ru/26iY9D2pFnuG/img-2015-11-19-17-32-45.png
НО! Back-end разработчики часто не используют label, а onclick вешают сразу на input
Добавьте в библиотеку обработчик события клика по псевдочекбоксу, который исполнит код onclick у input'a
```
<input id="inp" type="checkbox" onclick="console.log('=1');">
```
https://s.mail.ru/2bmPQZtQ7CF1/img-2015-11-19-17-34-47.png

**Comment by pafnuty** [comment]
Простите, **но такому разработчику надо бы железной линейкой по рукам надавать**, желательно ребром.
Мало того, что инлайн js само по себе зло, так ещё и навешивают несвойственные элементу, обработчики.
А если пользователь не кликнет по чекбоксу, а доберётся до него с помощью клавиатуры?

Используйте `.on()`

```js
$(document).on('change', '.checkbox', function(){
    console.log($(this).prop('value'));
});
```

**Comment by westyby** [comment]
Согласен, лучше вешать обработчик на изменение чекбокса, спасибо.

По поводу разработчика - слишком они большие http://bss-s.ru/
